### ISSUE TITLE
Error: Did not receive response in time for function ID 3

### ISSUE THREAD

**Issue by geertschuring** [Tinkerforge/rotary-poti-bricklet#1]
I've written a camel component that communicates with brickd using the java bindings. When I connect 3 rotary potentiometers to a single brick and try to configure all three simultaneously in my own java code I get the following error: 

```
3150 [Callback-Processor] ERROR nl.juniverse.tinkerforge.camel.rotarypoti.RotaryPotentiometerConsumer - Error setting bricklet configuration.
com.tinkerforge.TimeoutException: Did not receive response in time for function ID 3
    at com.tinkerforge.DeviceBase.sendRequest(DeviceBase.java:169)
    at com.tinkerforge.BrickletRotaryPoti.setPositionCallbackPeriod(BrickletRotaryPoti.java:264)
    at nl.juniverse.tinkerforge.camel.rotarypoti.RotaryPotentiometerConsumer.configureBricklet(RotaryPotentiometerConsumer.java:25)
    at nl.juniverse.tinkerforge.camel.TinkerforgeConsumer$3.enumerate(TinkerforgeConsumer.java:46)
    at com.tinkerforge.IPConnection.callEnumerateListeners(IPConnection.java:130)
    at com.tinkerforge.CallbackThread.dispatchPacket(IPConnectionBase.java:246)
    at com.tinkerforge.CallbackThread.run(IPConnectionBase.java:286)
```

This looks like a timing issue where to many simultaneous connections result in some of those exceeding the expected return time.

Reproduction scenario:
1. Connect 3 rotary potentiometers to a brick
2. Use the java bindings
3. Create 3 different connection objects, with each their own enumeration listener.
4. In the enumeration listener, create a new BrickletRotaryPoti object and call:

``` java
bricklet.setPositionCallbackPeriod(100);
bricklet.addPositionListener(this);
```

This results in 3 registered enumeration listeners that get called simultaneously.

**Important:**
- The problem does not occur when I artificially create a delay between the creation of the 3 different BrickletRotaryPoti objects, preventing them from being configured simultaneously.
- The problem also occurs when using linear potentionmeters in exactly the same setup.

**Comment by photron** [comment]
I did a simple test, but could not reproduce the problem yet.

What versions of brickd, Master Brick firmware, Bricklet firmware and Java bindings do you use? If you're not using the latest versions, does the problem go away if you update all of this components to the latest software version?

Can you create a minimal example that reproduces the problem?

**Comment by geertschuring** [comment]
Yes I'll try to create a standalone test that reproduces this.

**Comment by geertschuring** [comment]
If I could only attach files to this issue.....

**Comment by photron** [comment]
Just copy'n'paste the whole file as code block in a comment.

**Comment by geertschuring** [comment]
Allright. You'll have to build and install the camel-tinkerforge component manually because it is not in maven central yet. You can find it here: https://bitbucket.org/geertschuring/camel-tinkerforge/src

Connect 3 rotarypoti bricklets to your system.

Next, create a maven project with the following pom.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>nl.juniverse</groupId>
    <artifactId>camel-tinkerforge-demo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>nl.juniverse</groupId>
            <artifactId>camel-tinkerforge</artifactId>
            <version>2.12.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-core</artifactId>
            <version>2.12.1</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.1</version>
        </dependency>
    </dependencies>
</project>
```

Add the following file to the src/main/java directory:

``` java
package nl.juniverse.camel.tinkerforge.demo;

import org.apache.camel.CamelContext;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.impl.DefaultCamelContext;

public class PotentiometersDemo {
    public static void main(String[] args) throws Exception {

        CamelContext context = new DefaultCamelContext();

        context.addRoutes(new RouteBuilder() {
            public void configure() throws Exception {

                int interval = 100;

                from("tinkerforge:rotarypoti?uid=rp1&interval="+interval)
                .from("tinkerforge:rotarypoti?uid=rp2&interval="+interval)
                .from("tinkerforge:rotarypoti?uid=rp3&interval="+interval)
                .to("log:output?showHeaders=true");
            }
        });

        context.start();
        Thread.sleep(Long.MAX_VALUE);
    }
}
```

Don't forget to change the _uid_ parameter values to match your setup.

**Comment by photron** [comment]
Works for me.

I have brickd 2.1.1 running on Linux. The only connected Brick is a Master Brick (firmware 2.2.2) with three Rotary Poti Bricklets (firmware 2.0.2) connected to it (ports B, C and D).

Then I start the demo with this added to the pom.xml

``` xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <version>1.2.1</version>
    <configuration>
        <mainClass>nl.juniverse.camel.tinkerforge.demo.PotentiometersDemo</mainClass>
    </configuration>
</plugin>
```

using mvn exec:java.

No errors, just info messages for turning a poti.

**Comment by geertschuring** [comment]
I'm running brickd 2.1.1 on MacOS 10.10 (Yosemite). I have a stack of 2 bricks with 3 linear poti's connected to the first and 3 rotary poti's connected to the second brick. I'll check the bricks versions numbers tonight.

This problem is kind of a show stopper for multi source camel routes, so I would really appreciate if you could look into this. Let me know if I can do more testing for you.

**Comment by photron** [comment]
Could you test this example, does it reproduce the problem? I build this according to the description you gave. Did I match what your program does?

https://gist.github.com/photron/2edccb55a6c320723fd8

**Comment by geertschuring** [comment]
I've ran your test, and it does not reproduce the problem. I'll try to refactor your example so that it fails.

**Comment by geertschuring** [comment]
I've been able to reproduce the problem by refactoring your example. I've added the code as a comment on the gist: https://gist.github.com/photron/2edccb55a6c320723fd8#comment-1326497

**Comment by photron** [comment]
Still works for me, see my comment to the gits for more details.

**Comment by photron** [comment]
Closing issue, because there was no response for several years.
